name: simpegEM1D-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=20.3.1
  - python=3.6
  - SimPEG=0.13.1
  - jupyterlab
  - ipywidgets
  - pandas
  - ipykernel
  - voila
  - pip:
    - scipy==1.4.1
    - git+https://github.com/simpeg/simpegEM1D.git@master